### PR TITLE
Support multiple resource directories in aapt

### PR DESCRIPTION
**Pull request by shawnlauzon**
This is a fix for Issue #45: Support multiple resource directories in aapt

Rather than use the pluginConvention.resDir field, it allows you to set multiple resource directories into pluginConvention.resDirs, all of which are then passed to the aapt ant task.

I haven't used Groovy or Gradle much before, so if there's a preferred way of doing any of this, please let me know and I'll fix.

### CODE REVIEW

**Comment by ealden** [comment]
Thanks for this.  Let me find time to review and then merge if possible.

**Comment by ealden** [comment]
Hi @shawnlauzon, would it be possible to add an integration test for this specific scenario?

**Comment by shawnlauzon** [comment]
Yes, I'll add an integration test, but won't have time for a few days.

**Comment by shawnlauzon** [comment]
I'm having a problem running the tests. Here's the command I'm trying to run:

```
groovy -cp .:$GRADLE_HOME/lib/gradle-core-1.0-milestone-8a.jar:$GRADLE_HOME/lib/gradle-native-1.0-milestone-8a.jar com/jvoegele/gradle/android/HelloProjectTest.groovy
```

and the result is:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/Mac/Codez/git/gradle-android-plugin/src/integTest/groovy/com/jvoegele/gradle/android/support/TestProject.groovy: 21: unable to resolve class org.gradle.os.OperatingSystem
 @ line 21, column 1.
 import org.gradle.os.OperatingSystem
 ^
```

1 error

**Comment by ealden** [comment]
@shawnlauzon this was fixed in #50 - you should be able to merge master into this branch to get the fix.

**Comment by shawnlauzon** [comment]
First, I again apologize for taking so long to respond.
I have it merged, but I think I'm still having setup problems. First I set my CLASSPATH to:

```
/Users/Mac/Codez/gradle-1.0-milestone-8a/lib/gradle-core-1.0-milestone-8a.jar:/Users/Mac/Codez/gradle-1.0-milestone-8a/lib/gradle-cli-1.0-milestone-8a.jar:/Users/Mac/Codez/gradle-1.0-milestone-8a/lib/gradle-base-services-1.0-milestone-8a.jar:/Users/Mac/Codez/gradle-1.0-milestone-8a/lib/gradle-native-1.0-milestone-8a.jar:/Users/Mac/Codez/gradle-1.0-milestone-8a/lib/slf4j-api-1.6.4.jar:/Users/Mac/Codez/gradle-1.0-milestone-8a/lib/jna-posix-1.0.3.jar:/Users/Mac/Codez/gradle-1.0-milestone-8a/lib/guava-11.0.1.jar:/Users/Mac/Codez/slf4j-1.6.4/slf4j-simple-1.6.4.jar
```

and then I run the command:

```
groovy -DintegTest.androidProjects=. com/jvoegele/gradle/android/HelloProjectTest.groovy
```

But the result is:

```
JUnit 4 Runner, Tests: 6, Failures: 6, Time: 261
Test Failure: build(com.jvoegele.gradle.android.HelloProjectTest)
java.lang.SecurityException: Prohibited package name: java.util.zip
```

Do you have something that describes how to run the integration tests?

**Comment by ealden** [comment]
It should be possible to do: `./gradew developerBuild` to run the integration tests.  Let me know if that works for you.

**Comment by shawnlauzon** [comment]
Ahh, of course. Wow, that's a lot easier. Just need to fix my own test.

I'll add this to the instructions.

**Comment by shawnlauzon** [comment]
Integration test added! Let me know if you're looking for something more.

**Comment by ealden** [comment]
@shawnlauzon sorry for only taking a look now.  I merged this in a test branch based on master and I am getting test failures:

```
Caused by: : aaptexec doesn't support the "manifestPackage" attribute
```

I am not sure if this is unique to me or not.  Does this happen to you?  I used R14, R15, and R16 with the same result.

**Comment by shawnlauzon** [comment]
Hmm, I unfortunately have a couple of my fixes mixed all together. The "manifestPackage" is support for the --rename-manifest-package on aapt, which was added to the aapt ant command in R17. That issue is supposed to go with #46, but unfortunately got combined into #47.

What do you think: should I create a new pull request which contains ONLY the appropriate fixes? Would that mean pulling your current master and then adding the appropriate fixes one-by-one? Or is there a better way?

Sorry, this is a bit new for me, but I want to learn and do it right.

**Comment by ealden** [comment]
@shawnlauzon yes that's correct.  Better to split in different branches and then have separate PRs for them.  That should give each PR one and only one focus.

I understand that you have a change that requires R17 - I'm trying to get #55 merged to master so we can proceed with R17-specific functionality.

**Comment by ealden** [comment]
@shawnlauzon I merged #55 to master, so you should be set to pull it and then create branches with R17-specific changes :)

**Comment by shawnlauzon** [comment]
@ealden Yes, I have no idea how the two issues got tangled, but clearly I just screwed up. I was wondering how best to untangle my mess. I will look into this tonight, thanks!

**Comment by shawnlauzon** [comment]
I created another pull request which doesn't contain the rest of the updates. Closing this one.

**Pull request closed without merging**
