### PR TITLE
Start emulator with gradle

### PR DESCRIPTION
**Pull request by x2on**
I use gradle with the STS Gradle Eclipse Plugin and don't want to start the android-emulator with command line. I write a basic task for this. You can define your emulator avd in your build.gradle.

### CODE REVIEW

**Comment by Ladicek** [comment]
This is quite simple, so I've got no problems with the idea or basic implementation. Two quick notes before merging:
1. The master branch is meant to support Gradle 0.9 now, so the 2a16bd3 commit should be left off. There is a gradle-1.0m2-support branch that contains exactly that change (and few more).
2. The SDK directory in EmulatorTask shouldn't be read directly from the environment variable. Take it from project.ant['sdk.dir'] (see AndroidPlugin class to find out, how the ant['sdk.dir'] value is discovered).

Are you willing to do this or should I (it's pretty simple)? Thanks for the contribution, anyway!

And if you want to use/develop Gradle Android Plugin in the future, please consider joining the mailing lists at http://code.google.com/p/gradle-android-plugin/

**Comment by x2on** [comment]
Thanks for your response. I changed the second one, but i don't know how to remove a commit from a pull request. Any ideas?

**Comment by Ladicek** [comment]
Well, you can't :-) That's why it's better to develop even such small things on separate branches -- you would create another branch, merge the first one, wipe that commit using 'git rebase -i', later commits would get another ID, and we would merge that second branch. The first one you would drop and all would be fine.

Now that you have it in your master branch, things get little difficult. I can merge your master and remove that commit -- but some commits would get another ID and history would diverge. That wouldn't be good for you, as jvoegele/master would never merge cleanly to your master again.

Can you _somehow_ move your changes to a branch and restore your master to original position (maybe using git push --force)?

**Comment by x2on** [comment]
Ok ;) I created an branch called 'x2on-emulator' and reverted the commits.

New commits to merge are 0f5bb8ed7c9e2693a42daf48e593b0a0a37fd43e and 0d6a00ed491ce6af0cd5e8dc826b91f047e1c41f

Thanks for your help.

**Comment by Ladicek** [comment]
Okay, GitHub closed this pull request automagically for me :-) Thanks for the contribution!

**Pull request merged**
