### PR TITLE
Plugin doesn't include external libraries

### PR DESCRIPTION
**Pull request by apechinsky**
Hi

Current version of plugin doesn't include external libs from 'libs' directory into the final APK.

I've added a fix.

### CODE REVIEW

**Comment by fdasoghe** [comment]
Thank you so much! We'll review your patch as soon as possible.

**Comment by jvoegele** [comment]
Merged in master.  Thank you for the patch!

**Comment by apechinsky** [comment]
Before the patch there was no way to add external libraries to an APK. The patch adds basic support  for external libraries by including jars from externalLibsDir. Maybe externalLibsDir is redundant but it correlates to Android's ant task.
More advanced solution should include jars from dependencies. Not sure that dependencies from "compile" and "runtime" configurations are suitable here. Probably we should define dedicated configuration for this purposes.

**Comment by fdasoghe** [comment]
I think this discussion is made obsolete by discussions on this matter on the devel group, here (http://groups.google.com/group/gradle-android-plugin-developers/browse_thread/thread/234ac463a2302e4a) and here (http://groups.google.com/group/gradle-android-plugin-developers/browse_thread/thread/870cd5aec8a9369d).
I agree with the idea of using dependencies. Why not to pull jars and classes from the runtime configuration? For what I know, its purpose is right this.

**Pull request merged**
