### PR TITLE
Ported to support building on r20 tools

### PR DESCRIPTION
**Pull request by cyph84**

### CODE REVIEW

**Comment by ealden** [comment]
Thanks @cyph84 will take a look and see if we can merge this.

**Comment by ndarilek** [comment]
Any updates on this request? Just ran into this problem myself with a new project that I'd hoped to switch to Gradle, but I can't use it under R20 and don't want to ask my developers to download and build a custom plugin just for this.

Thanks.

**Comment by sonata82** [comment]
Well at least I can confirm that this fix works. I tested it on r20.

**Comment by davidsowerby** [comment]
I know this is a "me too" but I'm in the same position as ndarilek - it has been a month now ...

**Comment by ndarilek** [comment]
Does anyone have the time/skill to maintain an official fork with this 
fix? Looks like this is abandoned and there are no alternatives.

I'm very new to Gradle and would rather not take it on.

**Comment by jvoegele** [comment]
On Aug 28, 2012, at 5:22 PM, Nolan Darilek wrote:

> Does anyone have the time/skill to maintain an official fork with this 
> fix? Looks like this is abandoned and there are no alternatives.
> 
> I'm very new to Gradle and would rather not take it on.

I've merged all pending pull requests and have deployed a 1.2.0-SNAPSHOT version of gradle-android-plugin with all pending fixes. If no major problems are discovered with the 1.2.0-SNAPSHOT version I will create a 1.2.0 release version and deploy to Maven Central.

## 

Jason Voegele
Exhilaration is that feeling you get just after a great idea hits you,
and just before you realize what is wrong with it.

**Pull request merged**
