### PR TITLE
When making a debug package, make it debuggable

### PR DESCRIPTION
**Pull request by nmx**
This patch adds the "--debug-mode" flag to the aapt commandline when creating a debug package.  This mimicks the "debug" target of the standard android Ant build script.  It addresses the issue raised here:

http://groups.google.com/group/gradle-android-plugin-users/browse_thread/thread/c0800793c47885b8

### CODE REVIEW

**Comment by ealden** [comment]
Thanks for the PR @nmx.  I haven't tested this yet but on first glance this change should also appear in r7 and r8 versions of AaptExecTask, which covers R7 and below and R8 to R13, respectively.

**Comment by nmx** [comment]
I know that --debug-mode was not an option in the first version of aapt but I am not sure exactly which version it was added in, and since I don't have earlier versions of the SDK tools to test with, I'm not positive whether it should be added to those other tasks or not.  I can try to find out which versions support it.

**Comment by nmx** [comment]
According to http://developer.android.com/sdk/tools-notes.html#notes the option was added in SDK 8.  So I'll add it to the r8 task but not the r7 task.

**Comment by ealden** [comment]
Hi @nmx sorry this PR lingered for so long!  I'll test this out tomorrow with some of our projects and merge as necessary.

**Comment by nmx** [comment]
Hi ealden,

Any luck with this?

**Comment by ealden** [comment]
@nmx just checked it out and it looks good.  Would it be possible to add an integration test for this before I merge?

**Comment by ealden** [comment]
@nmx I'm merging this in, as I took a look at the existing tests and there is one that references `configureDebug` so this should be good to go.  Thanks!

**Comment by nmx** [comment]
Thanks!  I did also look at adding assertions to those tests to actually validate whether the APK has the debuggable flag set (in other words, that my patch does what it was intended to do) but it requires calling out to aapt and parsing the output, and I haven't really had any time to do it.  I may be submitting a patch to add those assertions later.

**Pull request merged**
