### PR TITLE
Simplified apply

### PR DESCRIPTION
**Pull request by Ladicek**
I really wanted to be able to write apply plugin: 'android' in my build.gradle file, and since it is a matter of adding one file...

I also changed README.txt appropriately.

### CODE REVIEW

**Comment by mttkay** [comment]
Awesome. I was wondering, too, why this was not working before, since from the Gradle doc it was apparent that this is trivial to implement.

+1 please :-)

**Comment by jvoegele** [comment]
I have merged this into the master branch.

**Comment by mttkay** [comment]
was this part of the 0.9.7 release? Cause I still get the same error: "Plugin with id 'android' not found". Am I missing something? Here's my build script:

**build.gradle (root module):**
    // global properties
    env = System.getenv()
    androidHome = env['ANDROID_HOME']

```
apply from: 'android.gradle'

// artifact configuration
allprojects {
    apply plugin: 'maven' // we publish all artifacts to the local m2 repo
    apply plugin: 'android'

    group = 'com.qype.android'
    version = '3.1.0-SNAPSHOT'

    defaultTasks 'clean', 'build', 'install'    
}

subprojects {
    repositories {
        mavenLocal()
    }

    dependencies {
        compile fileTree(dir: 'lib', includes: ['*.jar'])
    }    
}
```

**android.gradle:**
    buildscript {
        repositories {
          mavenRepo(urls: 'http://jvoegele.com/maven2/')
        }
        dependencies {
          classpath 'com.jvoegele.gradle.plugins:android-plugin:0.9.7'
        }
    }

**Comment by mttkay** [comment]
Strange, not even the canonical class name syntax works anymore:

"Could not find property 'com' on root project 'qype-android'"

that's when I replace it with:
    apply plugin: com.jvoegele.gradle.plugins.android.AndroidPlugin

any ideas?

**Comment by mttkay** [comment]
weird, I find that it works when moving the 'apply plugin' call _inside_ android.gradle. I  don't understand. What's the difference between:

```
buildscript {
    repositories {
      mavenRepo(urls: 'http://jvoegele.com/maven2/')
    }
    dependencies {
      classpath 'com.jvoegele.gradle.plugins:android-plugin:0.9.7'
    }
}
apply plugin: 'android'
```

followed by an `apply from: 'android.gradle'` and

```
buildscript {
    println "RUNNING BUILD SCRIPT CONFIG"
    repositories {
      mavenRepo(urls: 'http://jvoegele.com/maven2/')
    }
    dependencies {
      classpath 'com.jvoegele.gradle.plugins:android-plugin:0.9.7'
    }
}
```

followed by a
    apply from: 'android.gradle'
    apply plugin: 'android'

shouldn't that be exactly the same??

**Pull request merged**
